# Generated by Django 5.2.8 on 2025-11-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('adminsetup', '0003_alter_job_experience_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to="'application/resumes'")),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='Apply', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsetup.job')),
                ('jobseeker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuserprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'jobseeker'), name='unique_application')],
            },
        ),
    ]
