# Generated by Django 5.2.8 on 2025-11-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsetup', '0002_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level')], max_length=20),
        ),
    ]
