# Generated by Django 5.2.8 on 2025-11-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsetup', '0003_alter_job_experience_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('action', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=255, null=True)),
                ('content_type_id', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'easy_audit_log',
                'managed': False,
            },
        ),
    ]
